sudo: false
language: java
jdk:
- oraclejdk8
before_install: git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git
  target/ci-tooling
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
  - secure: avLZc/698zPZLoxLXT69ikWC87Xq7FybMu84y6YVBWbWtb1F50+KNuIybSphXJdgEp7eN/S3BLCqCD9eJ0RPrXp/HXGGgP7XL3C4nQXMb7Z1Xb3ETROYi4QzeGsjxhLdkX70qpmnr7Bfaf6yKHcfKjEHwwnMfQ3HnKTZzX10sjLUclm/R023UUvB/j0/YRkIUm0JENN5zG8kUf6BgQX4eeCW0AIbKFL7fPpxeNb88y2CsmpFHU8HzXkxU51BM+ODKUxMoMPoqBcjkuYRn/He24/yU2ZWcESmH3Hr21J4MKMfJDioPmFvwK2P143UJXfqFVhF2qlj3oXMuHfVcCh9XJ2pTTbw2AI5ZAsLpqUY3C+0gIfF+ydUlkvsVVAs4uzWotoQLfm9JFEiHfshpnWloA0QgGNh9xtAqXcsQDtnn46y3YhM/2GqRZES/FbhSjVngJFDZHUm0UetkhN3MECOhf5tslr3UYHSMz9qlT6orL8jLISmDjRBkE3G6g+upjw9XGH1su0FymfmmYeEG+WjnpMVaDLdZakE75b4fSyV4DN7rrBlh12HfE5lQ85qtSS11g8vPVl/r/AGbvCAKdH9bjc2GZgWEOLjP3lgmCz1jYmRfK5sDHJQB+HExbziIlwJXqiHae/A8Esk6XV9+Tct3/3txeBGNHS7M1wfMj7vpUc=
  - secure: tFAGRdW0RtU1ssp5CTLabv7EcXmpbBbKH1K0f/K7Dciz4vel0UKcosNDqzmUvqeKABnOTsOew1yMbp2yZ5aEF+J2sOSQFYQt/E8LC+YYRdNfuVcbKZSisDUTYC/c0odPePYzsX8nUamSgvJonjrLBROXv1wZ1SP5s4kQb+d7R5CDDxngHZ/mM981N8xTEPVa3gpHYaFiAP+T7TBibks5VqZZoAdvkGuANcyIPmFKr9ot7IU/Qhf/ZPMRUWZDq8bMIthV/OE0BfRh6eCjSE+cfH/IZRLTGLI+4PcGQTMNbQUycetXuYb4bl3msRrsTZ868Xpthi8mJohfbmlSs//omSzOdsn2Jt80F5U0fsoM9sjx0tU2dt23b+2GUMUyZHl6gNx9GJEMXAgYdq7fDepcD3TuLyqz939CPnP09Y1L4VdvgKxzF4wu8mVb5X5S8FR+AyJADdI2YAcWhpf/B/kZV0mfex3lfLbDX+H8tBIc+9PbuZaha811jyK693mLr1kwsm95SbUJsaAglZcSn+ggjAU9szJMlVmD87RogrYHiPcvvO54dNgZIgZgGDyk2bI+SKnOTGYb+m5WaD/xCygQ5mpOx36b+ieaEMmqLm6SEPGoSUxZzGfDhSOWLvTLyMWsKuFv1EO0dxcvbndSJz+5wRrF+OTjKM5UKJyBQFKDyBs=
